seed: 42
dataset: 
  seed: 42
  src_dir: /kaggle/input/dogcatdataset/kagglecatsanddogs_5340/PetImages
  tgt_dir: data/preprocessed
  train: 0.8
  dev: 0.1
  test: 0.1
  height: 32
  width: 32
  train_dir: data/preprocessed/train
  dev_dir: data/preprocessed/dev
  test_dir: data/preprocessed/test
  aug: False
  
model: 
  height: 32
  width: 32
  channels: 3
  num_classes: 2
  patch_size: 4
  hidden_size: 48
  num_attention_heads: 4
  intermediate_size: 192
  hidden_dropout_prob: 0.0
  attention_probs_dropout_prob: 0.0
  initializer_range: 0.02
  image_size: 32
  num_channels: 3

  dropout: 0.5

train:
  batch_size: 128
  epochs: 10
  learning_rate: 0.001
  optimizer: Adam
  ckpt_path: checkpoints/model_Adam.pth
  type: baseline
  weight_decay: 0
  aug: False
  patience: 3

device: cpu