seed: 42
dataset: 
  seed: 42
  src_dir: /kaggle/input/dogcatdataset/kagglecatsanddogs_5340/PetImages
  tgt_dir: data/preprocessed
  train: 0.8
  dev: 0.1
  test: 0.1
  height: 128
  width: 128
  train_dir: data/preprocessed/train
  dev_dir: data/preprocessed/dev
  test_dir: data/preprocessed/test
  aug: False
  
model: 
  height: 128
  width: 128
  channels: 3
  num_classes: 2
  hidden_size: 256
  dropout: 0

train:
  batch_size: 128
  epochs: 10
  learning_rate: 0.001
  optimizer: Adam
  ckpt_path: checkpoints/model_exp_2.pth
  type: exp_2
  weight_decay: 1e-3
  aug: True
  patience: 3

device: cuda